# render.yaml
version: "1"
services:
  - type: web
    name: tct
    runtime: docker
    repo: https://github.com/so-rce-code/test
    plan: free
    region: virginia
    dockerContext: .
    dockerfilePath: ./Dockerfile
    autoDeployTrigger: commit

    envVars:
      # Compulsory: must be set manually
      - key: SESSION_ID
        sync: false

      - key: TIMEZONE
        sync: false

      - key: PREFIX
        sync: false

      - key: DASHBOARD_USER
        sync: false

      - key: DASHBOARD_PASS
        sync: false

      # Defaults provided (optional, can be overridden)
      - key: server_port
        value: "3010"
