# render.yaml
version: "1"
services:
  - type: web
    name: tct
    runtime: docker
    repo: https://github.com/tct9428/tct
    plan: free
    region: virginia
    dockerContext: .
    dockerfilePath: ./Dockerfile
    autoDeployTrigger: commit

    envVars:
      # Compulsory: must be set manually
      - key: SESSION_ID
        sync: false

      # Defaults provided (can be overridden in dashboard)
      - key: PREFIX
        value: "."
        sync: false
      - key: server_port
        value: "3003"
        sync: false
      - key: DASHBOARD_USER
        value: "admin"
        sync: false
      - key: DASHBOARD_PASS
        value: "tct"
        sync: false
      - key: TIMEZONE
        value: "Africa/Nairobi"
        sync: false
