# render.yaml
version: "1"
services:
  - type: web
    name: tct
    runtime: docker
    repo: https://github.com/tct9428/tct
    plan: free
    region: virginia
    dockerContext: .
    dockerfilePath: ./Dockerfile
    autoDeployTrigger: commit

    envVars:
      # Compulsory: must be set manually
      - key: SESSION_ID
        sync: false

      # Defaults provided (optional, can be overridden)
      - key: PREFIX
        value: "."
        sync: true
      - key: server_port
        value: "3010"
      - key: DASHBOARD_USER
        value: "admin"
        sync: true
      - key: DASHBOARD_PASS
        value: "tct"
        sync: true

      - key: TIMEZONE
        sync: false
